/**
 * Sürekli ücretsiz (F2P) bilinen başlıklar — CheapShark’ta aranıp eşleşme alınır.
 * Geçici “%100 indirimle ücretsiz” teklifleri ayrı filtreyle elenir.
 */
export const F2P_POPULAR_SEEDS: readonly string[] = [
  'League of Legends',
  'Fortnite',
  'Roblox',
  'PUBG BATTLEGROUNDS',
  'PUBG',
  'Apex Legends',
  'Valorant',
  'Dota 2',
  'Counter-Strike 2',
  'Counter-Strike Global Offensive',
  'Warframe',
  'Destiny 2',
  'Path of Exile',
  'Genshin Impact',
  'Albion Online',
  'Lost Ark',
  'Call of Duty Warzone',
  'World of Tanks',
  'Team Fortress 2',
  'EVE Online',
  'Rocket League',
  'Fall Guys',
  'Halo Infinite',
  'Paladins',
  'Smite',
  'Brawlhalla',
  'MultiVersus',
  'World of Warships',
  'RuneScape',
  'Old School RuneScape',
  'Neverwinter',
  'Star Trek Online',
  'Marvel Snap',
  'Yu-Gi-Oh Master Duel',
  'Magic The Gathering Arena',
  'Gwent',
  'Hearthstone',
  'Diablo Immortal',
  'Honkai Star Rail',
  'Zenless Zone Zero',
  'The Finals',
  'Once Human',
  'Deadlock',
  'War Thunder',
  'Crossout',
  'Enlisted',
  'Splitgate',
  'CRSED F.O.A.D.',
]
